### ISSUE TITLE
What happens when a key is too short?

### ISSUE THREAD

**Issue by froglegseternal** [creaktive/tsh#8]
So, your algorithm 'accepts any key length'. However, this.... doesn't make much sense to me? From what I'm reading, it seems like the secret needs to be exactly 128 bits. I'm having a hard time parsing through your code, so I was just wondering if you remember what happens when the secret is too short.

**Comment by faizalam1** [comment]
```
sha1_starts( &sha1_ctx );
sha1_update( &sha1_ctx, (uint8 *) key, strlen( key ) );
sha1_update( &sha1_ctx, IV, 20 );
sha1_finish( &sha1_ctx, buffer );

aes_set_key( &pel_ctx->SK, buffer, 128 );
```
As you can see the key + iv is hashed and 16 bytes of hash is the key for AES BTW it is quite common in cryptosystem to use hash of keys rather than key because it is more secure and we dont have to limit ourselves to provide a fixed key.
